# Generated by Django 5.2.4 on 2025-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=100)),
                ('dificultad', models.CharField(max_length=50)),
            ],
        ),
    ]
