# Generated by Django 5.2.4 on 2025-07-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_curso_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='curso',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
